In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    'Student': ['Mahi', 'Ritvik', 'Mira', 'Sumit', 'Manvi'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female'],
    'Department': ['CS', 'DS', 'CS', 'DS', 'CS'],
    'Math': [85, 72, 91, 68, 88],
    'Physics': [78, 81, 89, 74, 93],
    'Chemistry': [92, 88, 95, 79, 90]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
print("First 5 rows: ")
display(df.head());
print("\nDataset Shape: ", df.shape)


First 5 rows: 


,Student,Gender,Department,Math,Physics,Chemistry
0,Mahi,Female,CS,85,78,92
1,Ritvik,Male,DS,72,81,88
2,Mira,Female,CS,91,89,95
3,Sumit,Male,DS,68,74,79
4,Manvi,Female,CS,88,93,90



Dataset Shape:  (5, 6)


In [ ]:
marks = df[['Math', 'Physics', 'Chemistry']].to_numpy()
print("Numpy Array: ")
print(marks)

Numpy Array: 
[[85 78 92]
 [72 81 88]
 [91 89 95]
 [68 74 79]
 [88 93 90]]


In [ ]:
print("Shape: ", marks.shape)
print("Size: ",  marks.size)
print("Dimensions: ", marks.ndim)

Shape:  (5, 3)
Size:  15
Dimensions:  2


In [ ]:
additional_marks = np.array([
    [5, 4, 3],
    [4, 5, 2],
    [3, 4, 5],
    [5, 3, 4],
    [2, 5, 3]
])
addition = marks + additional_marks
print("Addition: ")
print(addition)

subtraction = marks - additional_marks
print("\nSubtraction: ")
print(subtraction)

multiplication = marks * additional_marks
print("\nMultiplication: ")
print(multiplication)

transpose = marks.T
print("\nOriginal Matrix: ")
print(marks)
print("\nTranspose:")
print(transpose)

matrix_product = marks.T @ marks
print("\nMatrix Product: ")
print(matrix_product)

inverse = np.linalg.inv(matrix_product)
print("\nInverse of the matrix: ")
print(inverse)


Addition: 
[[ 90  82  95]
 [ 76  86  90]
 [ 94  93 100]
 [ 73  77  83]
 [ 90  98  93]]

Subtraction: 
[[80 74 89]
 [68 76 86]
 [88 85 90]
 [63 71 75]
 [86 88 87]]

Multiplication: 
[[425 312 276]
 [288 405 176]
 [273 356 475]
 [340 222 316]
 [176 465 270]]

Original Matrix: 
[[85 78 92]
 [72 81 88]
 [91 89 95]
 [68 74 79]
 [88 93 90]]

Transpose:
[[85 72 91 68 88]
 [78 81 89 74 93]
 [92 88 95 79 90]]

Matrix Product: 
[[33058 33777 36093]
 [33777 34691 36975]
 [36093 36975 39574]]

Inverse of the matrix: 
[[ 0.00838167 -0.00315882 -0.00469304]
 [-0.00315882  0.0081199  -0.00470566]
 [-0.00469304 -0.00470566  0.00870212]]


In [ ]:
encoded_df = df.copy()
encoded_df['Gender_Encoded'] = encoded_df['Gender'].map({'Female': 1, 'Male': 0})
encoded_df['Department_Encoded'] = encoded_df['Department'].map({'CS': 0, 'DS': 1})
print(encoded_df)

  Student  Gender Department  Math  Physics  Chemistry  Gender_Encoded  \
0    Mahi  Female         CS    85       78         92               1   
1  Ritvik    Male         DS    72       81         88               0   
2    Mira  Female         CS    91       89         95               1   
3   Sumit    Male         DS    68       74         79               0   
4   Manvi  Female         CS    88       93         90               1   

   Department_Encoded  
0                   0  
1                   1  
2                   0  
3                   1  
4                   0  


In [ ]:
print("Final Dataset: ")
print(encoded_df)

Final Dataset: 
  Student  Gender Department  Math  Physics  Chemistry  Gender_Encoded  \
0    Mahi  Female         CS    85       78         92               1   
1  Ritvik    Male         DS    72       81         88               0   
2    Mira  Female         CS    91       89         95               1   
3   Sumit    Male         DS    68       74         79               0   
4   Manvi  Female         CS    88       93         90               1   

   Department_Encoded  
0                   0  
1                   1  
2                   0  
3                   1  
4                   0  
